# Generated by Django 5.0.6 on 2024-05-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(default='red', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price',
            field=models.DecimalField(decimal_places=2, default='400.00', max_digits=6),
            preserve_default=False,
        ),
    ]
