# Generated by Django 5.0.6 on 2024-05-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cycling_store_app', '0004_alter_vehicle_color_alter_vehicle_number_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerorder',
            name='order',
            field=models.ManyToManyField(null=True, to='cycling_store_app.vehicle'),
        ),
    ]
